version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-manager-passwords-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - manager-passwords
    ports:
      - "${DB_PORT}:${DB_DOCKER_PORT}"

  web:
    build: .
    container_name: manager-passwords-app
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - KEY_ENCRYPTION=${KEY_ENCRYPTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_DOCKER_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - manager-passwords
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
    driver: local

networks:
  manager-passwords:
    driver: bridge